### ISSUE TITLE
Normalize the points to 0 to 1 for every decision

### ISSUE THREAD

**Issue by adhuri** [wddlz/fss16iad#6]
As of now all decisions are randomly generated from  observer min and max values for the decisions.

@wddlz  needs to do more experiment to find constraints on prism points to generate valid points.

@me need to normalize those decisions to toolbox.register("mutate", tools.mutGaussian, mu=0, sigma=1, indpb=0.2)

**Comment by wddlz** [comment]
Rules for ranges uploaded 194d448a8457f71dee90eda9d18fc488cb3db5a0

**Comment by adhuri** [comment]
Closing since this was not required explicitly.
